import { farmImages } from 'src/presentation/pages/add-farmer/components/farm-form/images';

// 🎯 DADOS BRASILEIROS REALISTAS
export const brazilianData = {
  names: [
    'João da Silva',
    'Maria Santos',
    'Pedro Oliveira',
    'Ana Costa',
    'Carlos Pereira',
    'Luiza Ferreira',
    'Bruno Almeida',
    'Camila Rodrigues',
    'Rafael Lima',
    'Juliana Mendes',
    'Antonio Souza',
    'Francisca Gomes',
    'José Roberto',
    'Mariana Carvalho',
    'Eduardo Barbosa',
    'Patrícia Ramos',
    'Felipe Martins',
    'Gabriela Duarte',
    'Lucas Moreira',
    'Fernanda Rocha',
    'Ricardo Nunes',
    'Aline Teixeira',
    'Thiago Cardoso',
    'Beatriz Figueiredo',
    'Gustavo Pinto',
    'Larissa Monteiro',
    'Vinícius Azevedo',
    'Amanda Ribeiro',
    'Leonardo Batista',
    'Paula Silveira',
    'Matheus Borges',
    'Isabela Souza',
    'Rodrigo Cunha',
    'Natália Lopes',
    'Marcelo Tavares',
    'Débora Pires',
    'André Castro',
    'Tatiane Almeida',
    'Fábio Fernandes',
    'Letícia Barros',
    'Diego Araújo',
    'Priscila Correia',
    'Renato Freitas',
    'Carolina Dias',
    'Sérgio Macedo',
    'Vanessa Moraes',
    'Alexandre Rezende',
    'Michele Santana',
    'Danilo Vieira',
    'Simone Guimarães',
  ],

  cities: [
    'Uberlândia',
    'Ribeirão Preto',
    'Barreiras',
    'Dourados',
    'Rio Verde',
    'Sorriso',
    'Sinop',
    'Primavera do Leste',
    'Campo Grande',
    'Rondonópolis',
    'Cascavel',
    'Ponta Grossa',
    'Maringá',
    'Londrina',
    'Chapecó',
    'Passo Fundo',
    'Luziânia',
    'Catalão',
    'Itumbiara',
    'Patos de Minas',
    'Montes Claros',
    'Araguaína',
    'Gurupi',
    'Balsas',
    'Imperatriz',
    'Paragominas',
    'Redenção',
    'Tangará da Serra',
    'Lucas do Rio Verde',
    'Alta Floresta',
    'Ji-Paraná',
    'Vilhena',
    'Ariquemes',
    'Naviraí',
    'Três Lagoas',
    'Corumbá',
    'Douradina',
    'Cuiabá',
    'Juína',
    'Barra do Garças',
    'Ituiutaba',
    'Frutal',
    'Uberaba',
    'Piracicaba',
    'Botucatu',
    'Ourinhos',
    'Assis',
    'Presidente Prudente',
    'Marília',
    'Tupã',
  ],

  states: [
    'MG',
    'SP',
    'GO',
    'MT',
    'MS',
    'PR',
    'RS',
    'BA',
    'TO',
    'MA',
    'PI',
    'CE',
    'PA',
    'RO',
    'RR',
    'AP',
    'AM',
    'AC',
    'PE',
    'PB',
    'RN',
    'AL',
    'SE',
    'ES',
    'RJ',
    'DF',
    'SC',
    'PB',
    'RN',
    'AL',
    'SE',
    'ES',
    'RJ',
    'DF',
    'SC',
    'PA',
    'RO',
    'RR',
    'AP',
    'AM',
    'AC',
    'PE',
    'PB',
    'RN',
    'AL',
    'SE',
    'ES',
    'RJ',
    'DF',
    'SC',
  ],

  farmNames: [
    'Fazenda Santa Clara',
    'Sítio Boa Esperança',
    'Fazenda São João',
    'Rancho Alegre',
    'Fazenda Nova Era',
    'Sítio Primavera',
    'Fazenda Bela Vista',
    'Rancho do Sol',
    'Fazenda Três Irmãos',
    'Sítio Verde Vale',
    'Fazenda Campo Belo',
    'Rancho da Paz',
    'Fazenda São Pedro',
    'Sítio Recanto Feliz',
    'Fazenda Lago Azul',
    'Rancho Esperança',
    'Fazenda Morada do Sol',
    'Sítio Estrela Guia',
    'Fazenda Boa Vista',
    'Rancho dos Sonhos',
    'Fazenda Vale Verde',
    'Sítio Santa Luzia',
    'Fazenda Paraíso',
    'Rancho Horizonte',
    'Fazenda São José',
    'Sítio Bela Aurora',
    'Fazenda Monte Verde',
    'Rancho do Lago',
    'Fazenda Recanto Verde',
    'Sítio Nova Vida',
    'Fazenda Santa Maria',
    'Rancho Bela Vista',
    'Fazenda Estrela do Sul',
    'Sítio Vale Encantado',
    'Fazenda Boa União',
    'Rancho dos Amigos',
    'Fazenda Nova Esperança',
    'Sítio Três Marias',
    'Fazenda Santa Rita',
    'Rancho do Campo',
    'Fazenda São Francisco',
    'Sítio Recanto Verde',
    'Fazenda Bela União',
    'Rancho do Vale',
    'Fazenda Nova Aliança',
    'Sítio Santa Fé',
    'Fazenda São Gabriel',
    'Rancho do Cerrado',
    'Fazenda Vale do Sol',
  ],

  cropTypes: [
    'Soybean',
    'Corn',
    'Coffee',
    'Cotton',
    'Sugarcane',
    'Wheat',
    'Rice',
    'Beans',
    'Other',
  ],

  companies: [
    'Agropecuária Silva Ltda',
    'Fazendas Unidas S.A.',
    'AgroTech Brasil Ltda',
    'Cooperativa Rural do Centro-Oeste',
    'Plantio & Colheita Ltda',
    'Verde Campo S.A.',
    'Grãos do Brasil Ltda',
    'Agricultura Moderna S.A.',
    'Campo Fértil Ltda',
    'Safra Rica Agronegócios',
    'Terra Produtiva S.A.',
    'Cultivo Sustentável Ltda',
    'AgroVale do Cerrado Ltda',
    'Sementes do Futuro S.A.',
    'AgroBrasil Exportadora',
    'Cooperativa AgroSul',
    'Agropecuária Nova Geração',
    'Fazenda Horizonte Verde',
    'AgroNorte Insumos Ltda',
    'Campo Forte Agronegócios',
    'AgroMais Brasil S.A.',
    'Cooperativa União Rural',
    'AgroSol Nascente Ltda',
    'Fazenda Boa Terra',
    'AgroCana Brasil S.A.',
    'Verdejar Agropecuária',
    'AgroPampa Ltda',
    'Soluções Agrícolas do Oeste',
    'AgroPlan Agropecuária',
    'Fazenda Raízes do Campo',
    'AgroSul Export Ltda',
    'Cooperativa Semeando Futuro',
    'AgroForte Brasil S.A.',
    'Campo Limpo Agronegócios',
    'AgroViva Ltda',
    'Fazenda Nova Esperança',
    'AgroCerrado S.A.',
    'Cooperativa Terra Fértil',
    'AgroLeste Produtos Rurais',
    'Fazenda São Francisco',
    'AgroVerde Sustentável',
    'AgroRiqueza Ltda',
    'Campo Aberto Agronegócios',
    'AgroSul Minas S.A.',
    'Fazenda Bela Vista',
    'AgroUnião Ltda',
    'Cooperativa Rural do Sul',
    'AgroPioneira S.A.',
    'Fazenda Santa Luzia',
    'AgroNobre Brasil Ltda',
  ],

  observations: [
    'Propriedade com excelente potencial produtivo e localização privilegiada.',
    'Solo fértil e clima favorável para diversas culturas.',
    'Investimentos constantes em tecnologia e sustentabilidade.',
    'Histórico de altas produtividades e práticas sustentáveis.',
    'Área estratégica com fácil acesso a rodovias e portos.',
    'Infraestrutura moderna e bem conservada.',
    'Disponibilidade de água durante todo o ano.',
    'Equipe qualificada e gestão eficiente.',
    'Diversificação de culturas ao longo das safras.',
    'Proximidade de centros urbanos e mercados consumidores.',
    'Certificação ambiental e boas práticas agrícolas.',
    'Sistema de irrigação automatizado.',
    'Topografia favorável para mecanização.',
    'Excelente histórico de manejo integrado de pragas.',
    'Potencial para expansão de áreas cultiváveis.',
    'Alto índice de produtividade por hectare.',
    'Propriedade livre de passivos ambientais.',
    'Acesso facilitado para máquinas e implementos.',
    'Boa relação com fornecedores e parceiros locais.',
    'Área com potencial para agricultura de precisão.',
    'Investimento recente em energia solar.',
    'Propriedade com documentação regularizada.',
    'Ambiente propício para pecuária integrada.',
    'Bons índices de conservação do solo.',
    'Presença de áreas de preservação permanente.',
    'Logística eficiente para escoamento da produção.',
    'Uso de sementes certificadas e insumos de qualidade.',
    'Propriedade com histórico de exportação.',
    'Sistema de armazenamento próprio.',
    'Área apta para produção orgânica.',
    'Gestão financeira transparente e eficiente.',
    'Propriedade com baixo índice de infestação de pragas.',
    'Adoção de práticas de agricultura regenerativa.',
    'Participação em programas de certificação rural.',
    'Propriedade com potencial para turismo rural.',
    'Boa disponibilidade de mão de obra local.',
    'Área com potencial para fruticultura.',
    'Propriedade com acesso à internet de alta velocidade.',
    'Investimento em capacitação de funcionários.',
    'Propriedade com histórico de premiações agrícolas.',
    'Área com potencial para silvicultura.',
    'Propriedade com baixo custo operacional.',
    'Participação ativa em associações rurais.',
    'Propriedade com áreas de lazer e convivência.',
    'Sistema de monitoramento climático instalado.',
    'Propriedade com potencial para produção de sementes.',
    'Área com boa drenagem natural.',
    'Propriedade com histórico de sustentabilidade.',
    'Propriedade com potencial para integração lavoura-pecuária.',
    'Área com fácil acesso a serviços e insumos agrícolas.',
  ],

  producerImages: [
    'https://randomuser.me/api/portraits/men/32.jpg',
    'https://img.freepik.com/fotos-gratis/homem-de-tiro-medio-que-vive-no-campo_23-2150642378.jpg?w=360',
    'https://img.freepik.com/fotos-premium/uma-mulher-jardineira-em-um-avental-esta-em-um-campo-de-grama-verde-ao-ar-livre-sorrindo-em-um-dia-de-verao-em-um-por-do-sol-foto-de-alta-qualidade_163305-252226.jpg?semt=ais_hybrid&w=740',
    'https://img.freepik.com/fotos-gratis/cena-fotorrealista-de-uma-fazenda-avicola-com-pessoas-e-galinhas_23-2151462271.jpg?semt=ais_hybrid&w=740',
    'https://img.freepik.com/fotos-gratis/agricultora-relaxando-ao-ar-livre_23-2149066196.jpg?semt=ais_hybrid&w=740',
    'https://wordpress-cms-gc-prod-assets.quero.space/uploads/2023/12/mulher-segurando-uma-cesta-cheia-de-legumes-com-espaco-de-copia-1-scaled.jpg',
    'https://imagens.ne10.uol.com.br/veiculos/_midias/jpg/2020/02/04/806x444/1_agricultores-604884.jpg',
    'https://img.freepik.com/fotos-gratis/homem-africano-colhendo-legumes_23-2151441203.jpg',
    'https://img.freepik.com/fotos-gratis/vista-fotorrealista-de-uma-mulher-colhendo-em-um-jardim-organico-sustentavel_23-2151462979.jpg?semt=ais_hybrid&w=740',
    'https://img.freepik.com/fotos-gratis/mulher-fotorrealista-em-um-jardim-organico-sustentavel-colhendo-produtos_23-2151462990.jpg?semt=ais_hybrid&w=740',
  ],

  farmImages: [
    'https://external-preview.redd.it/CHnUmFYnkdTcTDjiFLxad-vG2smC2Q_EWqv1FY8xskc.jpg?auto=webp&s=f787d1d5e57a925221264827db8d7fb9ce49727c',
    'https://c0.wallpaperflare.com/preview/803/343/639/brazil-pedra-preta-fazenda-farm.jpg',
    'https://wallpapers.com/images/hd/farm-desktop-ct4tnwgupjq73d1r.jpg',
    'https://wallpapers.com/images/hd/farm-desktop-bt3zi2c3bigi5qzd.jpg',
    'https://www.10wallpaper.com/wallpaper/1280x800/1304/farmland-creative_design_HD_wallpaper_1280x800.jpg',
    'https://cdn.pixabay.com/photo/2017/07/24/20/08/farmhouse-2535919_1280.jpg',
    'https://wallpapers.com/images/hd/farm-desktop-mfxczkefra7wv582.jpg',
    'https://wallpapers.com/images/hd/landscape-pictures-5cls1ruxkmiwa154.jpg',
    'https://www.produzindocerto.com.br/wp-content/uploads/2022/03/blog-caseprodutor-14-03.jpg',
    'https://blog.7mboots.com.br/wp-content/uploads/2025/02/blog-4240.jpg',
  ],

  cropImages: {
    SOYBEAN: [
      'https://t4.ftcdn.net/jpg/01/97/51/95/360_F_197519511_13yz5XbqMwLm1sG7kc8X1rDkyLpGflbX.jpg',
      'https://st4.depositphotos.com/1480128/27809/i/450/depositphotos_278091096-stock-photo-soybean-field-rows.jpg',
      'https://st2.depositphotos.com/30188930/50753/i/450/depositphotos_507534514-stock-photo-soybean-field-ripening-at-spring.jpg',
      'https://blog.verde.ag/pt/wp-content/uploads/2023/12/Ciclo-da-soja.-descubra-a-duracao-as-etapas-e-as-principais-fatores-que-o-influenciam.jpg',
      'https://img.freepik.com/fotos-premium/soja-fresca-na-palma-da-mao_712131-2346.jpg?semt=ais_items_boosted&w=740',
    ],
    CORN: [
      'https://tecseed.com.br/wp-content/uploads/2021/09/milho-doce-hibrido-sv-9298-sn2.jpg',
      'https://plus.unsplash.com/premium_photo-1664299124175-e2c793325bfa?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8bWlsaG98ZW58MHx8MHx8fDA%3D',
      'https://sna.agr.br/wp-content/uploads/2016/02/milho-capa-708.png',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjbdTrLnzt-XW8EMwttWk-ON2f4e0h7iw4oLoEM2l1Yju7NHlEIvIwb9b6VTMQzBIPTgswMW2zny1IzItSTAs_6l5Vfa0HdGSk6m6YRwjJlu9BTIV0-ZPgaEf_ItTvO_3UPicYVRapiq478/s1600/DSC00164.JPG',
      'https://img.freepik.com/fotos-premium/grao-de-milho-cozido-em-branco_64161-28.jpg',
    ],
    COFFEE: [
      'https://i.pinimg.com/736x/95/66/3f/95663f10d4647758d559f2e87e9f3065.jpg',
      'https://wallpapers.com/images/hd/coffee-background-t0c3wh99fpnzgto4.jpg',
      'https://images.unsplash.com/photo-1495774856032-8b90bbb32b32?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Y2FmJUMzJUE5fGVufDB8fDB8fHww',
      'https://c4.wallpaperflare.com/wallpaper/258/801/308/coffee-4k-computer-hd-download-wallpaper-preview.jpg',
      'https://www.plenocafe.com.br/templates/rt_supra/custom/images/graosnatura.jpg',
    ],
    COTTON: [
      'https://files.agro20.com.br/uploads/2019/11/%C3%93leo-de-algod%C3%A3o-2.jpg',
      'https://www.cnabrasil.org.br/storage/arquivos/imagens/_861x298_crop_center-center_100_none/128206/51419341932_53e1057e51_c.webp',
      'https://img.freepik.com/fotos-gratis/plantacao-de-cultivo-de-algodao-perto-das-estacoes-de-colheita_1268-29294.jpg?semt=ais_items_boosted&w=740',
      'https://s2-g1.glbimg.com/pXa2UoJM6SWPDNyaXw9SzBIt708=/0x0:3602x2398/984x0/smart/filters:strip_icc()/s.glbimg.com/jo/g1/f/original/2011/05/25/algodao_de_caroco.jpg',
      'https://vitat.com.br/wp-content/uploads/2021/03/depositphotos_10198711_xl-2015-m-scaled-e1614611053583.jpg?ims=fit-in/310x310/filters:quality(70):format(webpp)',
    ],
    SUGARCANE: [
      'https://img.freepik.com/fotos-premium/plantas-de-cana-de-acucar-crescem-no-campo_9185-337.jpg?semt=ais_hybrid&w=740',
      'https://media.istockphoto.com/id/93541349/pt/foto/planta%C3%A7%C3%A3o-de-cana-de-a%C3%A7%C3%BAcar.jpg?s=612x612&w=0&k=20&c=ZRpByAhao1xj9tNO3ChNE6VlP67rPDXQuXVWEX_NLVs=',
      'https://blog.esteiogestao.com.br/wp-content/uploads/2022/06/xDesign-sem-nome-15.jpg.pagespeed.ic.gOyzHMlBPT.jpg',
      'https://maisagro.syngenta.com.br/media/uploads/2023/10/imagem_2_cana-mitos-e-verdades-sobre-maturacao-pre-colheita.jpg',
      'https://maisagro.syngenta.com.br/media/uploads/2023/10/IMAGEM_2_21-herbishow-syngenta-participara-com-inovacoes-para-a-cana.jpg',
    ],
    WHEAT: [
      'https://media.istockphoto.com/id/119165809/pt/foto/plano-aproximado-de-orelhas-de-trigo-maduro.jpg?b=1&s=612x612&w=0&k=20&c=GCqxd53D0o1ibYyR0bahNjaGGQDRIj2-gQqSmMEN0sQ=',
      'https://aditivosingredientes.com/upload_arquivos/202204/202204-2d81baf6c08962b7a6fb25aa7c441390.jpg',
      'https://cdn.pixabay.com/video/2018/07/14/17285-280038627_tiny.jpg',
      'https://images.unsplash.com/photo-1529511582893-2d7e684dd128?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE1fHx8ZW58MHx8fHx8',
      'https://maisagro.syngenta.com.br/media/uploads/2023/10/trigo_confira_as_boas_praticas_para_uma_lavoura_saudavel_842x384.jpg',
    ],
    RICE: [
      'https://static.nationalgeographicbrasil.com/files/styles/image_3200/public/arroz-com-casca-e-arroz-branco.webp?w=1600&h=1071',
      'https://eos.com/wp-content/uploads/2023/04/rice-field.jpg.webp',
      'https://s2-receitas.glbimg.com/Df6g6Oh0QU7becimHQBi16t7ldM=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2023/n/c/ZHRaRXR8u4L2aimrF5XA/arroz-branco-receita.jpg',
      'https://down-br.img.susercontent.com/file/br-11134207-7r98o-lzzd5mbte71hf0',
      'https://down-br.img.susercontent.com/file/br-11134207-7r98o-ltegxng4kgmw0f',
    ],
    BEANS: [
      'https://www.observatorioagro.sc.gov.br/wp-content/uploads/2024/03/scs204Feijao-Predileto-Chapeco-36-scaled.jpg',
      'https://ecrie70.com.br/sistema/conteudos/imagem/g_66_0_1_06062023100506.jpg',
      'https://assets.revistacultivar.com.br/d87a1aad-5cd2-4058-ab75-402ef73cb8af.jpg',
      'https://s2-g1.glbimg.com/fy-XrJifAv1Pny2KIrLZLeR4kDY=/0x0:640x426/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/f/y/hRJd26TAACeARS5TPybw/brs-jurua.jpg',
      'https://assets.revistacultivar.com.br/d87a1aad-5cd2-4058-ab75-402ef73cb8af.jpg',
    ],
    OTHER: [
      'https://content.paodeacucar.com/wp-content/uploads/2020/06/alimentos-in-natura-capa.jpg',
      'https://uploads.diariodopara.com.br/2024/09/9QLHghKd-up_ag_59288_ea516520-4a2d-3dd1-3d22-2404c846cd5b-jpg.webp',
      'https://fesaude-bucket.s3.us-east-1.amazonaws.com/vegetais_89fe72812e.jpg',
      'https://cdn.esbrasil.com.br/wp-content/uploads/2019/06/alimentos_credito-shutterstock.jpg',
      'https://gravidezsaudavel.com.br/wp-content/uploads/2019/09/alimentos-in-natura-minimo-processamento.jpg.webp',
    ],
  },
};
